### ISSUE TITLE
"I don’t have a comments system"

### ISSUE THREAD

**Issue by tomlankhorst** [travisdowns/travisdowns.github.io#8]
> **Comments**
> I don’t have a comments system, but I’m working on it (read: occasionally complaining out load that comments on a static site are hard).

Possible solution: 

[StackOverflow: How do I use disqus comments in github pages blog](https://stackoverflow.com/questions/21446165/how-do-i-use-disqus-comments-in-github-pages-blog-markdown)

**Comment by travisdowns** [comment]
Thanks. I had previously excluded disqus from considerations because I didn't want ads or javascript bogging down my site and wanted to own the comment content (e.g., in case I wanted to migrate providers).

That said, I since learned that there is a free tier without ads (for now), so it's definitely a backup plan if something lighter weight doesn't emerge.

**Comment by travisdowns** [comment]
@tomlankhorst comments system finally added in 5005f7b87da33308c18e1ac01c505506fd093055 and subsequent changes. I went with staticman and describe the process [here](https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html).
